name: build-check

on:
  push:
    branches-ignore:
      - master
      - release
      - feature/deploy
  workflow_call:

env:
  STORE_PATH:

jobs:
  build-lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.8.0

      - name: install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.9.1
          run_install: false

      - name: get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: install dependencies
        run: pnpm i

      - name: setup build cache
        uses: actions/cache@v3
        with:
          path: ./dist/
          key: ${{ runner.os }}-build-dist-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-build-dist-

      - name: build
        run: pnpm build

      - name: lint
        run: pnpm lint
